#!/bin/bash
INIT_FLAG="Env init done"

if grep -q "$INIT_FLAG" /etc/bash.bashrc
then
  echo "Env init done (before)"
else
  ln -sf /work/docker-setting/.gitconfig /home/ubuntu/.gitconfig
  ln -sf /work/docker-setting/id_rsa /home/ubuntu/.ssh/id_rsa

  # bash setting
  echo "export TERM=xterm-256color " >> /etc/bash.bashrc
  echo "bind '\"\e[5~\": history-search-backward'" >> /etc/bash.bashrc
  echo "bind '\"\e[6~\": history-search-forward'" >> /etc/bash.bashrc

  echo "# $INIT_FLAG" >> /etc/bash.bashrc
  echo "Env init done"
fi
