#!/bin/bash
INIT_FLAG="Env init done"
MY_HOME="/home/ubuntu"

if grep -q "$INIT_FLAG" /etc/bash.bashrc
then
  echo "Env init done (before)"
else
  # gemset
  chown -R root:rvm /usr/local/rvm/gems
  source /usr/local/rvm/scripts/rvm
  rvm ruby-2.0.0-p481 --create
  rvm ruby-2.1.10 --create

  # git setting
  ln -sf /work/docker-setting/.gitconfig $MY_HOME/.gitconfig

  # ssh setting
  ln -sf /work/docker-setting/id_rsa $MY_HOME/.ssh/id_rsa
  cat /work/docker-setting/id_rsa.pub >> $MY_HOME/.ssh/authorized_keys
  chown ubuntu:ubuntu $MY_HOME/.ssh/authorized_keys

  # bash setting
  echo "export TERM=xterm-256color " >> /etc/bash.bashrc
  echo "bind '\"\e[5~\": history-search-backward'" >> /etc/bash.bashrc
  echo "bind '\"\e[6~\": history-search-forward'" >> /etc/bash.bashrc

  echo "# $INIT_FLAG" >> /etc/bash.bashrc
  echo "Env init done"
fi
