#!/bin/bash
INIT_FLAG="Env init done"
MY_HOME="/home/ubuntu"
MY_SHELL="/etc/bash.bashrc"

if grep -q "$INIT_FLAG" $MY_SHELL
then
  echo "Env init done (before)"
else
  # gemset
  source /usr/local/rvm/scripts/rvm
  rvm ruby-2.0.0-p481 --create
  rvm ruby-2.1.10 --create
  chown -R root:rvm /usr/local/rvm/gems

  # git setting
  ln -sf /work/docker-setting/.gitconfig $MY_HOME/.gitconfig

  # ssh setting
  ln -sf /work/docker-setting/id_rsa $MY_HOME/.ssh/id_rsa
  cat /work/docker-setting/id_rsa.pub >> $MY_HOME/.ssh/authorized_keys
  chown ubuntu:ubuntu $MY_HOME/.ssh/authorized_keys

  # bash setting
  ## terminal
  echo "export TERM=xterm-256color " >> $MY_SHELL

  ## key binding
  echo "bind '\"\e[5~\": history-search-backward'" >> $MY_SHELL
  echo "bind '\"\e[6~\": history-search-forward'" >> $MY_SHELL

  ## locale
  echo "export LC_CTYPE=zh_TW.UTF-8" >> $MY_SHELL
  echo "export LC_MESSAGES=zh_TW.UTF-8" >> $MY_SHELL
  echo "export LC_TIME=zh_TW.UTF-8" >> $MY_SHELL

  # set init flag
  echo "# $INIT_FLAG" >> $MY_SHELL
  echo "Env init done"
fi
